{% set name = "aws-c-common" %}
{% set version = "0.4.57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2b28a1aaf32c1b5230e4778f7edf3b53e1a690a1a742557ff489e09780db419a
  patches:
    - no-werror.patch
    - 0001-Don-t-hardcode-the-CoreFoundation-path.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-common", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-common${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/common/config.h  # [unix]
    - test -f $PREFIX/lib/cmake/AwsCFlags.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-common.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\aws\\common\\config.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\AwsCFlags.cmake exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-common
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.

extra:
  recipe-maintainers:
    - xhochy
