{% set name = "aws-c-common" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a4e7ac6c6f840cb6ab56b8ee0bcd94a61c59d68ca42570bca518432da4c94273

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-common", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - ninja-base
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-common${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/common/config.h  # [unix]
    - test -f $PREFIX/lib/cmake/aws-c-common/modules/AwsCFlags.cmake  # [unix]
    - test -f $PREFIX/lib/cmake/aws-c-common/modules/AwsFindPackage.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-common.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\aws\\common\\config.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\aws-c-common\\modules\\AwsCFlags.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\aws-c-common\\modules\\AwsFindPackage.cmake exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-common
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.
  description: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.
  doc_url: https://github.com/awslabs/aws-c-common#readme
  dev_url: https://github.com/awslabs/aws-c-common

extra:
  recipe-maintainers:
    - xhochy
