{% set name = "aws-c-common" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0b7705a4d115663c3f485d353a75ed86e37583157585e5825d851af634b57fe3
  patches:
    - patches/0001-Explicitly-remove-Werror.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-common", max_pin="x.x.x") }}

requirements:
  build:
    # - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - ninja-base
    - cmake >=3.9

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-common${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/common/config.h  # [unix]
    - test -f $PREFIX/lib/cmake/aws-c-common/modules/AwsCFlags.cmake  # [unix]
    - test -f $PREFIX/lib/cmake/aws-c-common/modules/AwsFindPackage.cmake  # [unix]
    - if not exist %LIBRARY_BIN%\aws-c-common.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\aws\common\config.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\aws-c-common\modules\AwsCFlags.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\aws-c-common\modules\AwsFindPackage.cmake exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-common
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.
  description: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.
  doc_url: https://github.com/awslabs/aws-c-common#readme
  dev_url: https://github.com/awslabs/aws-c-common

extra:
  recipe-maintainers:
    - xhochy
